### ISSUE TITLE
\cvskill{XX}{1} is not showing progress bar filled completely

### ISSUE THREAD

**Issue by evensure** [polyluxus/polycv#6]
`\cvskill{XX}{1}` (and thereby `\cvlanguage{XX}{1}` as well) is not working properly as the outcoming progress bar looks like the one for a chosen value of `0.2`.

However, `\cvskill{XX}{0.999999}` is a functioning workaround.

Edit: A look into the doc could have also helped: 
> \progressbar{full}% filled 100% (always) <

`\cvskill{XX}{full}` works flawlessly ;-)

**Comment by polyluxus** [comment]
Indeed this works as intended. Within the implementation of the skills and levels (making them work the same) there was this strange double meaning of `1`, which could no longer be interpreted as 100% (or full bar). I stumbled across this myself, and did not find an easy way to fix this. I shortly considered typification, i.e. `1` (int) vs. `1.0` (float), but got stuck on that as I couldn't find a proper way to check this. Hence only values strictly smaller than `1` will be taken as a fraction. Any number larger will be taken as the numerator to a skill fraction, with the denominator be set in the preamble and defaults to five. Therefore with `1` the bar will be set at `0.2`. The full bar will be set with any non-numerical input, too. That is a cheeky workaround, but it does the job unambiguously, which I was aiming for in the first release.
Thanks for bringing this up though (and finding the solution, too).
